apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 3  
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: zkdltid/go-app-test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080